# Generated by Django 5.2.5 on 2025-08-21 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=800)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=700)),
                ('author', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='veiculos.section')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='veiculos.vehicle')),
            ],
            options={
                'ordering': ['-published_at', '-captured_at'],
                'indexes': [models.Index(fields=['published_at'], name='noticias_ne_publish_9ef6f8_idx'), models.Index(fields=['title'], name='noticias_ne_title_e882ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'url'), name='uniq_news_vehicle_url')],
            },
        ),
    ]
