# Generated by Django 5.2.5 on 2025-08-21 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('media_type', models.CharField(choices=[('site', 'Site'), ('blog', 'Blog'), ('magazine', 'Magazine'), ('television', 'Television'), ('radio', 'Radio'), ('podcast', 'Podcast'), ('videocast', 'Videocast')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='veiculos_ve_name_5825fc_idx'), models.Index(fields=['media_type'], name='veiculos_ve_media_t_d83b07_idx'), models.Index(fields=['status'], name='veiculos_ve_status_40f924_idx')],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='veiculos.vehicle')),
            ],
            options={
                'ordering': ['vehicle__name', 'name'],
                'unique_together': {('vehicle', 'name')},
            },
        ),
    ]
