# Generated by Django 5.2.5 on 2025-08-21 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short label for this import', max_length=150)),
                ('editorial_xpaths', models.TextField(help_text='One XPath per line that extracts editorial URLs from the vehicle homepage.')),
                ('listing_link_xpath', models.TextField(help_text='XPath that extracts article links from a section page.')),
                ('article_section_name_xpath', models.TextField(blank=True, help_text='Optional: XPath to extract section name inside article.')),
                ('article_date_xpath', models.TextField(blank=True)),
                ('article_title_xpath', models.TextField()),
                ('article_subtitle_xpath', models.TextField(blank=True)),
                ('article_author_xpath', models.TextField(blank=True)),
                ('article_content_xpath', models.TextField()),
                ('interval_minutes', models.PositiveIntegerField(default=20)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('failed', 'Failed'), ('done', 'Done')], default='idle', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_configs', to='veiculos.vehicle')),
            ],
            options={
                'ordering': ['vehicle__name', 'name'],
                'unique_together': {('vehicle', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('failed', 'Failed'), ('done', 'Done')], default='running', max_length=10)),
                ('found_count', models.PositiveIntegerField(default=0)),
                ('new_count', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='importacoes.importconfig')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
