# Generated by Django 5.2.5 on 2025-08-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importconfig',
            name='editorial_xpaths',
            field=models.TextField(blank=True, help_text='1 XPath por linha. Cada linha extrai a URL do editoria'),
        ),
    ]
